MoocProj/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures do
    resources :comments
    member do
      put "like", to: "lectures#upvote"
      put "dislike", to: "lectures#downvote"
      put :add_to_spam
      delete :delete_from_spam
    end
  end
  resources :courses
  devise_for :users

  root 'courses#index'

end

MoocProj/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  belongs_to :Course
  belongs_to :User
  has_many :comments, :dependent => :delete_all;
  has_and_belongs_to_many :users
  acts_as_votable

  #validation
  validates :content , :presence => true
  validates :content, length: { in: 10..500 }

  validates :Course_id , :presence => true
  validates :User_id , :presence => true

  validate :attachment_size_validation, :if => "attachment?"

  def attachment_size_validation
    errors[:attachment] << "should be less than 1MB" if attachment.size > 1.megabytes
  end

end

MoocProj/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy, :add_to_spam, :delete_from_spam]
  before_action :authenticate_user!

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
      @comments=Comment.where(lecture_id: @lecture).order("created_at DESC")
  end


  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.User_id=current_user.id

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json

  def update
    @lecture.User_id=current_user.id
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
  @lecture = Lecture.find(params[:id])
  @lecture.upvote_by current_user
    redirect_to @lecture
  end

def downvote
  @lecture = Lecture.find(params[:id])
  @lecture.downvote_by current_user
  redirect_to @lecture
end

def add_to_spam
  current_user.lectures << @lecture
  current_user.save

  redirect_to lectures_path
end

def delete_from_spam
  current_user.lectures.delete(@lecture)
  current_user.save

  redirect_to lectures_path
end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:content, :attachment, :Course_id, :User_id)
    end
end

MoocProj/app/helpers/lectures_helper.rb
module LecturesHelper
end

MoocProj/app/views/lectures/_form.html.erb
  <%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@lecture.errors.count, "error") %>
      prohibited this lecture from being saved:</h2>

    <ul>
      <% @lecture.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content ,class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>

  <div class="field">
    <%= f.label :Course_id %><br>
    <%= f.collection_select :Course_id ,Course.all ,:id,:title ,class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-info'%>
  </div>
  <% end %>

MoocProj/app/views/lectures/edit.html.erb
<div class="container">
  <h1>Editing Lecture</h1>
  <%= render 'form' %>

  <%= link_to 'Show', @lecture ,{ :class=>"btn btn-info" }%>
  <%= link_to 'Back', lectures_path ,{ :class=>"btn btn-info" }%>
</div>

MoocProj/app/views/lectures/index.html.erb
<div class="container">
  <h1>Listing Lectures</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Content</th>
        <th>Attachment</th>
        <th>Course</th>
        <th>User</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @lectures.each do |lecture| %>
      <tr>
        <td><%=raw lecture.content %></td>
        <td><%= link_to 'Show Attachment', lecture.attachment.url %></td>
        <td><%= lecture.Course.title %></td>
        <td><%= lecture.User.name %></td>
        <td><%= link_to 'Show', lecture %></td>
        <% if lecture.User.id==current_user.id %>
        <td><%= link_to 'Edit', edit_lecture_path(lecture)%></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?',:class=>"btn btn-info" }%></td>
        <% end %>
        <% unless current_user.lectures.include?(lecture) %>
        <td><%= link_to 'Spam', add_to_spam_lecture_path(lecture), method: :put %></td>
        <% else %>
        <td><%= link_to 'Unspam', delete_from_spam_lecture_path(lecture), method: :delete %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'New Lecture', new_lecture_path ,{ :class=>"btn btn-info" }%>
</div>

MoocProj/app/views/lectures/new.html.erb
<div class="container">
<h1>New Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>
</div>

MoocProj/app/views/lectures/show.html.erb
<div class="jumbotron">
  <h1 class="container"><%= @lecture.Course.title%></h1>
  <h3 class="container">By :
    <%= @lecture.User.name %>
  </h3>
  <p class="container"><%=raw @lecture.content %></p>
  <div class="container">
  <%= link_to 'Show Attachment', @lecture.attachment.url ,{ :class=>"btn btn-info" }%>
  </div>
</div>

<div class="row container">
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail text-center">
      <%= link_to like_lecture_path(@lecture), method: :put do %>
      <%=image_tag("thumb_up.png", :width => 50, :height => 50)%>
      Like
      <%= @lecture.get_upvotes.size %>
      <% end %>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail text-center">
      <%= link_to dislike_lecture_path(@lecture), method: :put do %>
      <%=image_tag("thumb_down.png", :width => 50, :height => 50)%>
      Dislike
      <%= @lecture.get_downvotes.size %>
      <% end %>
    </div>
  </div>
</div>

<hr>

<%= render 'comments/comment'%>

<hr>
<div class="container">
<% if @lecture.User.id==current_user.id %>
<%= link_to 'Edit', edit_lecture_path(@lecture),{ :class=>"btn btn-info" } %>
<% end %>
<%= link_to 'Back', lectures_path ,{ :class=>"btn btn-info" }%>
</div>