MoocProj/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures do
    resources :comments
    member do
      put "like", to: "lectures#upvote"
      put "dislike", to: "lectures#downvote"
      put :add_to_spam
      delete :delete_from_spam
    end
  end
  resources :courses
  devise_for :users

  root 'courses#index'

end

MoocProj/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @lectures=Lecture.where(Course_id: @course).order("created_at DESC")
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.User_id=current_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @course.user_id=current_user.id
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :User_id)
    end
end

MoocProj/app/helpers/courses_helper.rb
module CoursesHelper
end

MoocProj/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title ,class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-info'%>
  </div>
<% end %>

MoocProj/app/views/courses/edit.html.erb
<div class="container">
  <h1>Editing Course</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @course ,{ :class=>"btn btn-info" }%>

  <%= link_to 'Back', courses_path ,{ :class=>"btn btn-info" }%>
</div>

MoocProj/app/views/courses/index.html.erb
<div class="container">
  <h1>Listing Courses</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.User.name %></td>
        <td><%= link_to 'Show', course %></td>
        <% if course.User.id==current_user.id %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Course', new_course_path ,{ :class=>"btn btn-info" }%>
</div>

MoocProj/app/views/courses/new.html.erb
<div class="container">
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>
</div>

MoocProj/app/views/courses/show.html.erb
<div class="jumbotron">
  <h1 class="container">Title:
    <%= @course.title %></h1>
  <h3 class="container">By :
    <%= @course.User.name %>
  </h3>

</div>

<div class="list-group container">
  <div class="list-group-item active">
    <%= @course.title %> lectures :
  </div>
  <% @lectures.each do |lecture| %>
  <%= link_to lecture.id, lecture ,{ :class=>"list-group-item" }%>
  <% end %>
</div>

<div class="container">
  <% if @course.User.id==current_user.id %>
  <%= link_to 'Edit', edit_course_path(@course) ,{ :class=>"btn btn-info" }%>
  <% end%>
  <%= link_to 'Back', courses_path ,{ :class=>"btn btn-info" }%>
</div>